### ISSUE TITLE
The moodle-drupalservices plugin does not allow users to sign in and settings to be changed.

### ISSUE THREAD

**Issue by pdm1976** [cannod/moodle-drupalservices#54]
Hi all,

Suddenly this plugin is giving me problems. I tried looking for a solution but find myself stuck.

Problem: The plugin does not allow drupal users to sign in on Moodle: the name and password are not accepted and no new user is created in Moodle. The drupalservices settings-page only displays the Drupal webpage url. The rest of the page is white.

Drupal version 7.35
Moodle version 2.8.5+ (Build: 20150313)

Drupal and Moodle are both installed in their own subdirectory. The traffic is redirected to mydomain.com for Drupal and academy.mydomain.com for Moodle. It has worked like this correctly since before the sso login problems began.

Drupal side
Moodle SSO module installed (7.x-1.x-dev)

Moodle side:
Drupalservices plugin installed: the current master version (2.x - alpha) (2014123000)

In the <drupal>/sites/default folder I have changed settings.php so that the relevant line is uncommented and now shows:
$cookie_domain = '.mydomain.com';

In Moodle under administration>server>session handling I tried changing the empty field of 'cookie domain' to ".mydomain.com" but that did not resolve anything so I've deleted that entry again.

With an earlier test setup (slightly older version of Drupal core and Moodle) I had this SSO solution working nicely. I then started updating and working on other functionalities within Drupal: multi-lingual, coupons, etc. I don't know what got changed but suddenly I noticed I could not get into Moodle anymore coming from Drupal. Luckily I did not define an alternative logon url within Moodle so I can still log in with my initial manual admin account.

At the moment I notice a few things:
(1) the sso plugin on the Moodle side lets me only define a Drupal URL, nothing else. The rest of the settings I could previously see are all gone. It's just white space.

(2) Running cron on Moodle shows me the following error:
Running cron for auth/drupalservices...
ERROR: Problems trying to get index of users!

(3) Going to mydomain.com/moodlesso/ gives the result:
Services Endpoint "moodlesso" has been setup successfully.

(4) When I run cron on Moodle I see the following lines show up in the Drupal Recent Hits report:
03/17/2015 - 15:34	Services endpoint 	moodlesso/user		Anonymous (not verified)	details
03/17/2015 - 15:34	Services endpoint	moodlesso/user/token	Anonymous (not verified)	details
03/17/2015 - 15:34	Services endpoint	moodlesso/user/login	<admin> *1			details
03/17/2015 - 15:34	Services endpoint	moodlesso/user/token	Anonymous (not verified)	details

In Drupal this admin-account also has the service-authentication role appointed.

(4) When I go directly to academy.mydomain/auth/drupalservices/settings.php I am presented with an error:

Warning: require_once(/authlib.php): failed to open stream: No such file or directory in /public_html/academy/auth/drupalservices/settings.php on line 22

Fatal error: require_once(): Failed opening required '/authlib.php' (include_path='.:/usr/local/php53/lib:/usr/lib/php:/usr/local/lib/php') in public_html/academy/auth/drupalservices/settings.php on line 22

When I go to academy.mydomain/auth/drupalservices/version.php I get a white page.

At the moment SSO does not seem to work at all but I am not sure how to isolate the problem, let alone fix it. Maybe I am even asking for the obvious. Does anyone have any suggestions? Please understand I am new at this and not proficient in writing code. Thank you very much in advance.

**Comment by pdm1976** [comment]
Does anybody know where I should look? I really need this to work. By the way, if I enable Moodle Debug messages, above the Drupal Services settings page it now shows "Notice: Trying to get property of non-object in /auth/drupalservices/REST-API.php on line 72"
At the moment I see nothing on this settings page except the field to define the Drupal url.

**Comment by netw3rker** [comment]
Hi @pdm1976 ,

It shouldn't matter, but if you are using drupal and moodle as separate subdirectories of your domain, you shouldn't need the ".mydomain.com" cookie value in your settings/config files.

have you run the moodle upgrade script recently? the particular error you are seeing looks like something that was resolved a while ago. also, make sure that you get your code from the 2.x-2.x branch of this repo rather than the master. There are some differences that can confound things.

**Comment by pdm1976** [comment]
Hi netw3rker,

Thank you for your help. Appreciated! I just commented the line in my settings/config files but that does not change anything. I also reinstalled the 2.x-2.x-dev branch again. I am running Moodle version 2.8.5+ (Build: 20150414). Under Site Admin>Notification I only see a mentioning of yet a newer version of Moodle (Build: 20150424) but I am guessing this can't be the problem.

Also, when I enable "Display debug messages" in Moodle pretty much every page under Site Administration starts with "Notice: Trying to get property of non-object in <path to my moodle directory>/auth/drupalservices/REST-API.php on line 72". I am kind of worried about that too.

In general: still no settings in the drupalservices config page (only the drupal url), no succesful login in moodle through the plugin, <drupal>/moodlesso shows "Services Endpoint "moodlesso" has been setup successfully." and <drupal>/moodlesso/moodlesso shows a xml file with the cookie domain.

**Comment by netw3rker** [comment]
well, you can try adding the following lines to your config.php file to force the settings:
```
$CFG->forced_plugin_settings['auth_drupalservices']['host_uri']='http://example.com';
$CFG->forced_plugin_settings['auth_drupalservices']['cookiedomain']='example.com';
```

those should get the ball rolling for you. You'll obviously need to change "example.com" to your domain, and you might need to do some tweaking to the cookiedomain, but that should be fine.

**Comment by pdm1976** [comment]
The drupalservices settings page now shows that the drupal website url was defined in config.php but furtherwise nothing has changed. I also still see the "Notice: Trying to get property of non-object in <my moodle folder>/auth/drupalservices/REST-API.php on line 72" above it because I enabled the debug messages.  I just wish I could isolate the problem first. I have no idea what the result should be if I go to <drupal>/moodlesso, or <drupal>/moodlesso/moodlesso. Nor what the drupal logs should show when moodle is trying to verify a username/password combination.

Is there a document somewhere that explains step by step how moodle and drupal should communicate here, what the expected outcome of each step is etc so I can pinpoint the problem? I am guessing I am asking for too much here. Do you maybe have a suggestion on how I should go about?

**Comment by netw3rker** [comment]
so this looks like a problem with your service responding with a CSRF token:
``` 
private function GetCSRFToken() {
    $url = $this->endpoint_uri . '/user/token';
    $response = $this->CurlHttpRequest('RemoteAPI->Token', $url, 'POST', "", true, true);
    if($response->info['http_code'] <> 200){
      return false;
    }
    return $response->response->token;
  }
```
Line 72 is the return of the token value, and appears to be a non-response.

One thing you can do to test this is get a REST client plugin (I use Advanced REST Client for chrome), and try to reach  example.com/moodlesso/user/token using an HTTP POST request. Take a look at the response and optionally include it here.

If I had to guess as to what is happening here, my guess would be this: you had a service defined with a machine name of moodlesso that you configured previously. Then you installed the moodle_sso module into Drupal (which also uses the moodlesso machine name for the service it defined). I'll bet, If you go to the features admin page, you'll see that the moodlesso feature shows overridden. If you go in and revert that feature and it's components, things will start working.

**Comment by pdm1976** [comment]
For this site I did a clean install. When I now go to the features admin page I see Moodle SSO under Moodle Tools. State is default and all dependent modules are enabled and show in green.

When I test the REST client with the Chrome extendion you mentioned I get back a token in HTTP POST (access denied in HTTP GET). Response headers with the HTTP POST call:

Date: Wed, 29 Apr 2015 08:59:35 GMT 
Server: Apache 
Expires: Sun, 19 Nov 1978 05:00:00 GMT 
Cache-Control: no-cache, must-revalidate, post-check=0, pre-check=0 
Vary: Accept 
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Transfer-Encoding: chunked 
Content-Type: text/yaml 

The response:
---
token: 3BJORFtXo3Sg8fVYQ6hI5V6qLRmIyYmV-Izju5tQMrY

Is this what is expected? Can I maybe give you more specific info? Tnx.

**Comment by netw3rker** [comment]
Wow, I really expected a non-value response! I think we are getting to the bottom of this though. Either a) you did that while logged in as admin vs as an anonymous user (not likely, but just to be sure try opening an incognito window, and using the REST checker on that url again) or, your server isn't able to make requests to itself (I think more likely).

Are you able to ssh in to your server and run command on the CLI? If so, try running
```
wget --post-data "" http://example.com/moodlesso/user/token
```
then review the file (probably called token) that gets written afterwards. My guess is that you'll get some kind of error when doing the wget, or the file will be blank.

**Comment by pdm1976** [comment]
When I use the chrome plugin the results are the same in a normal window or incognito for the HTTP POST. For both a get a token back (different ones because of, I assume, different sessions). With HTML GET the normal windows shows 'access denied for user <my username>' while in the incognito window ofcourse it says 'Access denied for user anonymous'. I think this is what you expect?

However, when I use PuTTY to ssh in to the server i get:

>wget --post-data "" http://www.(my_domain).com/moodlesso/user/token

result:
>Resolving www.(my_domain).com... failed: Name or service not known.
>wget: unable to resolve host address `www.(my_domain).com'

Or with the www
>wget --post-data "" http://(my_domain).com/moodlesso/user/token

result:
>Resolving (my_domain).com... x.x.x.x
>Connecting to (my_domain).com|x.x.x.x|:80... connected.
>HTTP request sent, awaiting response... 301 Moved Permanently
>Location: http://www.(my_domain).com/moodlesso/user/token [following]
>--2015-04-30 14:12:11--  http://www.(my_domain).com/moodlesso/user/token
>Resolving www.(my_domain).com... x.x.x.x
>Reusing existing connection to (my_domain).com:80.
>HTTP request sent, awaiting response... 403 : Access denied for user anonymous
>2015-04-30 14:12:12 ERROR 403: : Access denied for user anonymous.

After the 301 error I decided to comment out the following lines in the .htaccess file in root:
RewriteCond %{HTTP_HOST} .
RewriteCond %{HTTP_HOST} !^www\. [NC]
RewriteRule ^ http%{ENV:protossl}://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

When I run "wget --post-data "" http://(my_domain).com/moodlesso/user/token" again I now get:

>--2015-04-30 14:17:32--  http://(my_domain).com/moodlesso/user/token
>Resolving (my_domain).com... x.x.x.x
>Connecting to (my_domain).com|x.x.x.x|:80... connected.
>HTTP request sent, awaiting response... 200 OK
>Length: unspecified [text/yaml]
>Saving to: `token'
>
>[ <=>                                                                                                                ] 58          --.-K/s   in 0s
>
>2015-04-30 14:17:32 (2.84 MB/s) - `token' saved [58]

A step forward it seems?

Unfortunately it does not resolve the initial problem.  After I purge all caches and run cron I still only see the URL in the drupalservices admin page, login still don't work through this module.

Maybe worth mentioning, the cron displays the next feedback:

>Running auth crons if required...
>Running cron for auth/drupalservices...
>Notice: Trying to get property of non-object in <moodle_folder>/auth/drupalservices/REST-API.php >on line 72
>Notice: Trying to get property of non-object in <moodle_folder>/auth/drupalservices/REST-API.php >on line 242
>Notice: Trying to get property of non-object in <moodle_folder>/auth/drupalservices/REST-API.php >on line 243
>Notice: Trying to get property of non-object in <moodle_folder>/auth/drupalservices/REST-API.php >on line 72
>Notice: Undefined property: stdClass::$pagesize in <moodle_folder>/auth/drupalservices/auth.php >on line 279
>ERROR: Problems trying to get index of users!
>Fatal error: Uncaught exception 'coding_exception' with message 'Coding error detected, it must >be fixed by a programmer: \core\lock\lock() has fallen out of scope without being released.
>Locks must ALWAYS be released by calling $mylock->release().' in ><moodle_folder>/lib/classes/lock/lock.php:107>
Stack trace:
>#0 [internal function]: core\lock\lock->__destruct()
>#1 {main}
>  thrown in <moodle_folder>/lib/classes/lock/lock.php on line 107

I hope you are still willing to give me some advice. Tnx.

**Comment by netw3rker** [comment]
Well, that's a step forward :)

You should also make sure that when you edit the file (named token) that got created after calling ```wget``` that there's a value in there. I'm guessing there is.

Now the question is, how can we get that to return a result. One silly question for you though, have you made sure you are logged in to Drupal and have an active session before going to configure the Moodle settings? Also, do you still have the fixed values in your config.php file?

There aren't very many other reasons why this would return a bad value for token but I'll stick with you on this!

**Comment by pdm1976** [comment]
Excellent, that is good to hear! Tnx

Yes, I did check the token file and it indeed holds a value. Regarding the active session: yes, I first login with Drupal and then, in a second tab, go to Moodle. The admin username is not equal to the one in Drupal though but I assume this is ok. I did this on purpose after I once ran into problems as the drupalservices module was trying to create a new account in Moodle (based on the one from Drupal) whereas that name already existed in Moodle as a manually created account. Anyway, that was in the days it still worked.

The fixed values are indeed still in the config.php.

**Comment by netw3rker** [comment]
Well, I'm not 100% sure how to explain this... Would you like to get an interactive screen share session together in the next day or two & try to get this one resolved directly?

**Comment by pdm1976** [comment]
My apologies, I was completely off the grid for a couple of days. Such bad timing since I missed your message now but that would be great! How do we go about this? I think I just added you on twitter so we can communicate directly. Tnx!

**Comment by pdm1976** [comment]
A quick update. The earlier issues were caused by the token string having extra characters added. This was discovered by @netw3rker after he very kindly spent some of his time trying to help me out. It was explained to me that this was caused by some php-files having the byte order mark (BOM). I have cleaned my site directory (github.com/emrahgunduz/BomCleaner) and netw3rker has added some code to the REST-API.php in the 2.x-2.x-dev-branch.

After this was resolved I had the problem that (1) the login still did not work plus that (2) I could not define the user field mappings in the drupalservices plugin config page in Moodle.

After I made a few changes the logon now kinda works:
* Moodle: config.php. Add:
**$CFG->forced_plugin_settings['auth_drupalservices']['cookiedomain']='.mydomain.com';**
* Drupal: settings.php. Uncomment and change:
**$cookie_domain = '.mydomain.com';**
* Moodle SQL: mdl_config-table:
**set "sessioncookiedomain" to 'mydomain.com'**
* Delete all lokal cookies and purge site cache

Of course 'mydomain.com' was substituted by my actual domain name. I run both Moodle and Drupal from subdirectories.

When I (using an incognito browser window) login as a regular user in drupal and then go to Moodle I do not login automatically yet I can login manually using the drupal credentials. I am then immediately presented with the error:
>Notice: Undefined property: object::$id in /moodle/auth/drupalservices/auth.php on line 207
Warning: session_regenerate_id(): Cannot regenerate session id - headers already sent in moodle/lib/classes/session/manager.php on line 462

When I look in the sql db, Moodle immediately shows the new user in the user-table with most of the fields empty (as they have not been defined in the plugins config page I assume). When I look at issue #62 I see similar errors.

Does anybody know how I can fix the user field mappings to be defined and the login to work so that the user details are copied from the drupal db?

**Comment by goose2000** [comment]
I was able yesterday to go into the DB and I manually entered in the drupal fields and was able to get this to work. The Auth plugin interface is just a one-chance kind of form, You get one chance to map the fields when you are initially installing it, after that it gets locked up. Just shows '0' in the drop-downs.

![sso-fields](https://cloud.githubusercontent.com/assets/2395298/9523474/3d16586e-4ca8-11e5-84e0-e6fe3542fa06.png)

**Comment by pdm1976** [comment]
Thank you @goose2000 for the advice. I am starting to make progress here. Still some bugs to work out but it's looking good!

**Comment by pdm1976** [comment]
After cleaning up some old accounts in moodle it seems to be working now, finally! Very grateful for the help I received here. At the moment though I am still left with an error I mentioned before. When running cron on Moodle I get:

>Notice: Undefined property: stdClass::$pagesize in moodle/auth/drupalservices/auth.php on line 279
ERROR: Problems trying to get index of users!

This is referring to the following piece of code in auth.php:
>// list external users since last update
$vid=isset($this->config->last_vid)?$this->config->last_vid:0;
**$pagesize=$this->config->pagesize;**
$page=0;

**Comment by engr-noman** [comment]
@goose2000 sir i have integrated drupal with moodle its working but actually mapping is not working ,I have added fields to my user registeration form in drupal,like field_firstname,field_lastname,field_city,field_country but i am not getting its values in my moodle site,when i edit the setting of drupal service in plugin overview section i am unable to change or see those fields,it shows only 0 in dropdown,As you told that it is one time chance then it locked now please help me how to unlock those changes.And what is the problem with my mapping as username and pass working fine but the problem is only with firstname,surname,email,city,country.
